### ISSUE TITLE
buffdb requires SQLite version >= 3.35.0

### ISSUE THREAD

**Issue by hygoni** [buffdb/buffdb#15]
I encountered failures while running buffdb testcases:

```bash
failures:
    sqlite::blob::test_delete_no_metadata
    sqlite::blob::test_delete_with_metadata
    sqlite::blob::test_eq_data
    sqlite::blob::test_get
    sqlite::blob::test_not_eq_data
    sqlite::blob::test_query
    sqlite::blob::test_store
    sqlite::blob::test_update_both
    sqlite::blob::test_update_bytes
    sqlite::blob::test_update_metadata

test result: FAILED. 34 passed; 10 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.32s
```

After some investigation, it turns out that [RETURNING clause](https://www.sqlite.org/lang_returning.html) is not supported in my sqlite version (3.34).

**Comment by jhpratt** [comment]
Ah, this is because SQLite isn't vendored like DuckDB is. I'll likely end up adding an option to vendor it (and not requiring vendoring for DuckDB), at which point things can be documented in a manner appropriate to the situation.

**Comment by hygoni** [comment]
> Ah, this is because SQLite isn't vendored like DuckDB is. I'll likely end up adding an option to vendor it (and not requiring vendoring for DuckDB), at which point things can be documented in a manner appropriate to the situation.

By vendoring, do you mean including the SQLite and DuckDB source code, and then allowing the user to choose which to include in the binary, instead of choosing them at runtime as it is now?

**Comment by jhpratt** [comment]
Yes, that's exactly what I mean. I haven't documented it yet, but I pushed it to `main` just now. Thankfully it's a _very_ simple change.

**Comment by jhpratt** [comment]
Alright, documented now :+1: Vendoring is enabled by default, feature flags are documented, and a note has been added to try the vendored version if unexpected errors are encountered.
