### ISSUE TITLE
Add RocksDB backend support

### ISSUE THREAD

**Issue by hygoni** [buffdb/buffdb#17]
As it seems no one else is working on it, I'd like to take it on.

**Comment by jhpratt** [comment]
Feel free! You'll likely want to go through the commit history, as it was previously used as a backend (before more than one was supported). There will almost certainly be some changes you'll need to make, but I don't see it being too tricky. Also note that RocksDB will _not_ implement `Queryable`. If this causes any compilation errors in the binary, let me know.
