### ISSUE TITLE
Don't listen in the dynamic port range

### ISSUE THREAD

**Issue by fcantournet** [buffdb/buffdb#22]
50051 is in the [dynamic port range](https://en.wikipedia.org/wiki/Ephemeral_port).

buffdb should default to listening on a port in the valid port range for server.

**Comment by MarcusSorealheis** [comment]
@fcantournet 

You're totally right. Our open a PR to dix this right away. We had to shift priorities briefly for a moment here.

**Comment by MarcusSorealheis** [comment]
Fixed [here](https://github.com/buffdb/buffdb/commit/98a406884b2088ba6a11235b7e9dd3aa6ef7ab6c)
